---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
- name: centos-5.10
- name: centos-6.5
- name: centos-7.0
- name: ubuntu-10.04
  run_list: ["recipe[apt]"]
- name: ubuntu-12.04
  run_list: ["recipe[apt]"]
- name: ubuntu-14.04
  run_list: ["recipe[apt]"]
- name: debian-6.0.10
  run_list: ["recipe[apt]"]
- name: debian-7.6
  run_list: ["recipe[apt]"]
- name: fedora-19
- name: fedora-20
- name: freebsd-10.0
  run_list: ["recipe[freebsd::portsnap]"]

suites:
- name: default
  run_list:
  - recipe[mysql_tuning_test::default]
- name: lwrp
  run_list:
  - recipe[mysql_tuning_test::lwrp]
- name: ohai
  run_list:
  - recipe[mysql_tuning_test::ohai_plugin]
